export const APP_URL = 'https://wedding-invitation-98d6a.web.app/'
export const addGuestEndpoint = 'https://us-central1-wedding-invitation-98d6a.cloudfunctions.net/addGuest'
export const deleteGuestEndpoint = 'https://us-central1-wedding-invitation-98d6a.cloudfunctions.net/deleteGuest'
export const getAllGuestEndpoint = 'https://us-central1-wedding-invitation-98d6a.cloudfunctions.net/getAllGuests'
export const getGuestByIdEndpoint = 'https://us-central1-wedding-invitation-98d6a.cloudfunctions.net/getGuestById'
export const updateGuestEndpoint = 'https://us-central1-wedding-invitation-98d6a.cloudfunctions.net/updateGuest'